import { Hono, type Context } from 'hono';
import { getCookie, setCookie, deleteCookie } from 'hono/cookie';
import { z } from 'zod';
import { canModerate, canView, type Memory, type Profile, type Viewer, type ReviewStatus, type Photo } from '../src/shared';
import type { Store, UserRecord } from './store';
import { hashPassword, hashToken, id, newToken, verifyPassword } from './auth';

const visibility=z.enum(['public','alumni','hidden']);
const profileInput=z.object({name:z.string().trim().min(2).max(80),year:z.number().int().min(1900).max(2100),programId:z.string().min(1),motto:z.string().trim().min(2).max(180),bio:z.string().trim().max(1200),visibility,portrait:z.string().max(300).optional(),links:z.array(z.string().url().max(300)).max(3).default([])});
const memoryInput=z.object({title:z.string().trim().min(3).max(120),body:z.string().trim().min(10).max(3000),year:z.number().int().min(1900).max(2100),schoolYear:z.string().trim().max(40).optional(),visibility,image:z.string().max(300).optional(),caption:z.string().trim().max(180).optional()});
const registerInput=z.object({name:z.string().trim().min(2).max(80),email:z.email().max(254),password:z.string().min(12).max(128),year:z.number().int(),programId:z.string(),evidence:z.string().trim().min(12).max(1000)});
const reviewInput=z.object({type:z.enum(['verification','profile','memory','photo','comment']),id:z.string(),status:z.enum(['published','rejected']),note:z.string().trim().max(500).default('')});
type Factory=(c:Context)=>Store;
const msg=(error:string)=>({error});
const visibleProfile=(p:Profile,v:Viewer)=>p.status==='published'&&canView(p.visibility,p.userId,v);
const visibleMemory=(m:Memory,v:Viewer)=>m.status==='published'&&canView(m.visibility,m.ownerId,v);
function asViewer(user:UserRecord|null):Viewer{return user?{id:user.id,name:user.name,role:user.role,verified:user.verified}:null}
async function viewer(c:Context,s:Store){const cookie=getCookie(c,'ag_session');if(!cookie)return null;const sess=await s.session(await hashToken(cookie));return sess?asViewer(await s.userById(sess.userId)):null}
async function body<T>(c:Context,schema:z.ZodType<T>):Promise<T>{return schema.parse(await c.req.json())}
function audited(s:Store,actor:string,action:string,target:string){return s.addAudit({id:id(),actor,action,target,createdAt:new Date().toISOString()})}
export function createApi(factory:Factory,options:{demo:boolean;origin:string|((c:Context)=>string);email?:(c:Context,to:string,subject:string,body:string)=>Promise<void>}){
 const app=new Hono();
 app.onError((e,c)=>{if(e instanceof z.ZodError)return c.json(msg(e.issues.map(x=>x.message).join('; ')),400);console.error(e);return c.json(msg('Something went wrong. Please try again.'),500)});
 app.use('/api/*',async(c,next)=>{if(!['GET','HEAD','OPTIONS'].includes(c.req.method)){const origin=c.req.header('origin');if(origin&&origin!==(typeof options.origin==='string'?options.origin:options.origin(c)))return c.json(msg('Invalid request origin'),403)}await next()});
 app.get('/api/health',async c=>{await factory(c).batches();return c.json({ok:true,mode:options.demo?'demo':'production'})});
 app.get('/api/bootstrap',async c=>{const s=factory(c),v=await viewer(c,s),bs=await s.batches(),ps=await s.programs(),all=await s.memories(),prof=await s.profiles();return c.json({viewer:v,batches:bs,programs:ps,featured:all.filter(x=>x.featured&&visibleMemory(x,v)).slice(0,3),stats:{alumni:prof.filter(x=>visibleProfile(x,v)).length,years:bs.length,memories:all.filter(x=>visibleMemory(x,v)).length},demo:options.demo})});
 app.get('/api/me',async c=>{const s=factory(c),v=await viewer(c,s);if(!v)return c.json(msg('Sign in required'),401);return c.json({viewer:v,profile:(await s.profiles()).find(x=>x.userId===v.id)||null,memories:(await s.memories()).filter(x=>x.ownerId===v.id),verification:(await s.verifications()).find(x=>x.userId===v.id)||null})});
 app.post('/api/auth/register',async c=>{const s=factory(c),x=await body(c,registerInput),email=x.email.toLowerCase();if(await s.userByEmail(email))return c.json(msg('An account already uses this email.'),409);if(!(await s.batches()).some(b=>b.year===x.year)||!(await s.programs()).some(p=>p.id===x.programId))return c.json(msg('Choose a listed graduation year and program.'),400);const u:UserRecord={id:id(),email,name:x.name,role:'alumnus',verified:false,passwordHash:await hashPassword(x.password)};await s.createUser(u);await s.saveVerification({id:id(),userId:u.id,name:x.name,year:x.year,programId:x.programId,evidence:x.evidence,status:'pending',createdAt:new Date().toISOString()});await audited(s,u.id,'verification submitted',u.id);await signIn(c,s,u);if(options.email){try{await options.email(c,u.email,'Your Alumni Gallery request','Your request is pending school review. You can draft your profile and memories while you wait.')}catch(e){console.error('Email delivery failed',e)}}return c.json({viewer:asViewer(u),status:'pending'},201)});
 app.post('/api/auth/login',async c=>{const s=factory(c),x=await body(c,z.object({email:z.email(),password:z.string()})),u=await s.userByEmail(x.email.toLowerCase());if(!u||!(await verifyPassword(x.password,u.passwordHash)))return c.json(msg('Email or password is incorrect.'),401);await signIn(c,s,u);return c.json({viewer:asViewer(u)})});
 app.post('/api/auth/logout',async c=>{const s=factory(c),token=getCookie(c,'ag_session');if(token)await s.deleteSession(await hashToken(token));deleteCookie(c,'ag_session',{path:'/'});return c.json({ok:true})});
 async function signIn(c:Context,s:Store,u:UserRecord){const token=newToken();await s.putSession({tokenHash:await hashToken(token),userId:u.id,expiresAt:new Date(Date.now()+7*86400000).toISOString()});setCookie(c,'ag_session',token,{httpOnly:true,secure:!options.demo,sameSite:'Strict',path:'/',maxAge:7*86400})}
 app.get('/api/profiles',async c=>{const s=factory(c),v=await viewer(c,s),q=(c.req.query('q')||'').toLowerCase().trim(),year=Number(c.req.query('year')||0),program=c.req.query('program'),sort=c.req.query('sort')||'name',page=Math.max(1,Number(c.req.query('page')||1)),limit=12;if(s.directory)return c.json(await s.directory({q,year,program:program||'',sort,page,viewer:v}));let list=(await s.profiles()).filter(x=>visibleProfile(x,v)&&(!q||x.name.toLowerCase().includes(q)||x.motto.toLowerCase().includes(q))&&(!year||x.year===year)&&(!program||x.programId===program));list.sort(sort==='year'?(a,b)=>b.year-a.year||a.name.localeCompare(b.name):sort==='year-asc'?(a,b)=>a.year-b.year||a.name.localeCompare(b.name): (a,b)=>a.name.localeCompare(b.name));return c.json({items:list.slice((page-1)*limit,page*limit),total:list.length,page,pages:Math.max(1,Math.ceil(list.length/limit))})});
 app.get('/api/profiles/:id',async c=>{const s=factory(c),v=await viewer(c,s),p=(await s.profiles()).find(x=>x.id===c.req.param('id'));if(!p||!(visibleProfile(p,v)||v&&(v.id===p.userId||canModerate(v))))return c.json(msg('Profile not found'),404);const photos=(await s.photos()).filter(x=>x.ownerId===p.userId&&(x.status==='published'||v&&(v.id===p.userId||canModerate(v))));return c.json({profile:{...p,photos},memories:(await s.memories()).filter(x=>x.ownerId===p.userId&&visibleMemory(x,v))})});
 app.get('/api/batches/:year',async c=>{const s=factory(c),v=await viewer(c,s),year=Number(c.req.param('year')),batch=(await s.batches()).find(x=>x.year===year);if(!batch)return c.json(msg('Graduation year not found'),404);return c.json({batch,profiles:(await s.profiles()).filter(x=>x.year===year&&visibleProfile(x,v)),memories:(await s.memories()).filter(x=>x.year===year&&visibleMemory(x,v))})});
 app.get('/api/memories',async c=>{const s=factory(c),v=await viewer(c,s),year=Number(c.req.query('year')||0),page=Math.max(1,Number(c.req.query('page')||1)),limit=9;const all=(await s.memories()).filter(x=>visibleMemory(x,v)&&(!year||x.year===year)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const items=await Promise.all(all.slice((page-1)*limit,page*limit).map(async x=>({...x,reactionCount:await s.reactionCount(x.id),reacted:v?await s.hasReacted(x.id,v.id):false,commentCount:(await s.comments(x.id)).filter(y=>y.status==='published').length})));return c.json({items,total:all.length,page,pages:Math.max(1,Math.ceil(all.length/limit))})});
 app.get('/api/memories/:id',async c=>{const s=factory(c),v=await viewer(c,s),m=(await s.memories()).find(x=>x.id===c.req.param('id'));if(!m||!(visibleMemory(m,v)||v&&(v.id===m.ownerId||canModerate(v))))return c.json(msg('Memory not found'),404);return c.json({memory:{...m,reactionCount:await s.reactionCount(m.id),reacted:v?await s.hasReacted(m.id,v.id):false},authorProfileId:(await s.profiles()).find(p=>p.userId===m.ownerId&&visibleProfile(p,v))?.id,comments:(await s.comments(m.id)).filter(x=>x.status==='published'||v&&(x.userId===v.id||canModerate(v)))})});
 app.put('/api/me/profile',async c=>{const s=factory(c),v=await viewer(c,s);if(!v)return c.json(msg('Sign in required'),401);const x=await body(c,profileInput);if(!(await s.batches()).some(b=>b.year===x.year)||!(await s.programs()).some(p=>p.id===x.programId))return c.json(msg('Choose a listed year and program.'),400);const old=(await s.profiles()).find(p=>p.userId===v.id);if(x.portrait&&x.portrait!==old?.portrait&&!await ownedPhoto(s,x.portrait,v.id))return c.json(msg('Choose a photo you uploaded.'),400);const p:Profile={id:old?.id||id(),userId:v.id,...x,status:'pending'};await s.saveProfile(p);await audited(s,v.id,'profile submitted',p.id);return c.json({profile:p})});
 app.post('/api/memories',async c=>{const s=factory(c),v=await viewer(c,s);if(!v)return c.json(msg('Sign in required'),401);const x=await body(c,memoryInput);if(!(await s.batches()).some(b=>b.year===x.year))return c.json(msg('Choose a listed graduation year.'),400);if(x.image&&!await ownedPhoto(s,x.image,v.id))return c.json(msg('Choose a photo you uploaded.'),400);const m:Memory={id:id(),ownerId:v.id,author:v.name,...x,status:'pending',featured:false,createdAt:new Date().toISOString(),reactionCount:0,commentCount:0};await s.saveMemory(m);await audited(s,v.id,'memory submitted',m.id);return c.json({memory:m},201)});
 app.put('/api/memories/:id',async c=>{const s=factory(c),v=await viewer(c,s);if(!v)return c.json(msg('Sign in required'),401);const m=(await s.memories()).find(x=>x.id===c.req.param('id'));if(!m||m.ownerId!==v.id)return c.json(msg('Memory not found'),404);const x=await body(c,memoryInput);if(x.image&&x.image!==m.image&&!await ownedPhoto(s,x.image,v.id))return c.json(msg('Choose a photo you uploaded.'),400);const updated={...m,...x,status:'pending' as ReviewStatus,featured:false,reviewNote:''};await s.saveMemory(updated);await audited(s,v.id,'memory edited',m.id);return c.json({memory:updated})});
 app.delete('/api/memories/:id',async c=>{const s=factory(c),v=await viewer(c,s);if(!v)return c.json(msg('Sign in required'),401);const m=(await s.memories()).find(x=>x.id===c.req.param('id'));if(!m||m.ownerId!==v.id)return c.json(msg('Memory not found'),404);await s.saveMemory({...m,status:'archived',featured:false});await audited(s,v.id,'memory archived',m.id);return c.json({ok:true})});
 app.post('/api/photos',async c=>{const s=factory(c),v=await viewer(c,s);if(!v)return c.json(msg('Sign in required'),401);const form=await c.req.raw.formData(),file=form.get('file');if(!(file instanceof File))return c.json(msg('Choose an image.'),400);if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024||file.size===0)return c.json(msg('Use a JPG, PNG, or WebP image under 5 MB.'),400);const bytes=await file.arrayBuffer();if(!validImage(new Uint8Array(bytes),file.type))return c.json(msg('The file does not match its image type.'),400);const key=v.id+'/'+id()+'.'+(file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg'),photo:Photo={id:id(),ownerId:v.id,key,alt:String(form.get('alt')||'').slice(0,180),caption:String(form.get('caption')||'').slice(0,180),status:'pending',visibility:'hidden'};if(!s.putPhotoBytes)return c.json(msg('Photo storage is unavailable.'),503);await s.putPhotoBytes(key,bytes,file.type);await s.savePhoto(photo);await audited(s,v.id,'photo uploaded',photo.id);return c.json({photo:{...photo,url:'/api/photos/'+photo.id}},201)});
 app.get('/api/photos/:id',async c=>{const s=factory(c),v=await viewer(c,s),p=(await s.photos()).find(x=>x.id===c.req.param('id'));if(!p)return c.json(msg('Photo not found'),404);const owner=!!v&&(v.id===p.ownerId||canModerate(v));const referenced=(await s.profiles()).some(x=>x.portrait==='/api/photos/'+p.id&&visibleProfile(x,v))||(await s.memories()).some(x=>x.image==='/api/photos/'+p.id&&visibleMemory(x,v));if(!owner&&!(p.status==='published'&&referenced&&canView(p.visibility,p.ownerId,v)))return c.json(msg('Photo not found'),404);const blob=await s.photoBytes?.(p.key);if(!blob)return c.json(msg('Photo unavailable'),404);return new Response(blob.data,{headers:{'content-type':blob.type,'cache-control':'private, no-store','x-content-type-options':'nosniff'}})});
 app.post('/api/memories/:id/react',async c=>{const s=factory(c),v=await viewer(c,s);if(!v?.verified)return c.json(msg('Verified alumni only'),403);const m=(await s.memories()).find(x=>x.id===c.req.param('id'));if(!m||!visibleMemory(m,v))return c.json(msg('Memory not found'),404);const reacted=await s.toggleReaction(m.id,v.id);return c.json({reacted,count:await s.reactionCount(m.id)})});
 app.post('/api/memories/:id/comments',async c=>{const s=factory(c),v=await viewer(c,s);if(!v?.verified)return c.json(msg('Verified alumni only'),403);const m=(await s.memories()).find(x=>x.id===c.req.param('id'));if(!m||!visibleMemory(m,v))return c.json(msg('Memory not found'),404);const x=await body(c,z.object({body:z.string().trim().min(2).max(600)})),comment={id:id(),memoryId:m.id,userId:v.id,author:v.name,body:x.body,status:'pending' as ReviewStatus,createdAt:new Date().toISOString()};await s.saveComment(comment);await audited(s,v.id,'comment submitted',comment.id);return c.json({comment},201)});
 app.post('/api/reports',async c=>{const s=factory(c),v=await viewer(c,s);if(!v?.verified)return c.json(msg('Verified alumni only'),403);const x=await body(c,z.object({targetType:z.enum(['memory','comment','profile']),targetId:z.string().min(1),reason:z.string().trim().min(8).max(500)}));let exists=false;if(x.targetType==='memory')exists=(await s.memories()).some(y=>y.id===x.targetId&&visibleMemory(y,v));if(x.targetType==='profile')exists=(await s.profiles()).some(y=>y.id===x.targetId&&visibleProfile(y,v));if(x.targetType==='comment')exists=(await s.comments()).some(y=>y.id===x.targetId&&y.status==='published');if(!exists)return c.json(msg('Content not found'),404);const report={id:id(),...x,reporterId:v.id,status:'open' as const,createdAt:new Date().toISOString()};await s.saveReport(report);await audited(s,v.id,'content reported',x.targetType+':'+x.targetId);return c.json({report},201)});
 app.get('/api/admin',async c=>{const s=factory(c),v=await viewer(c,s);if(!canModerate(v))return c.json(msg('Forbidden'),403);const [vs,ps,ms,cs,photos,reports,audits,users]=await Promise.all([s.verifications(),s.profiles(),s.memories(),s.comments(),s.photos(),s.reports(),s.audits(),s.profiles()]);return c.json({verification:vs.filter(x=>x.status==='pending'),profiles:ps.filter(x=>x.status==='pending'),memories:ms.filter(x=>x.status==='pending'),comments:cs.filter(x=>x.status==='pending'),photos:photos.filter(x=>x.status==='pending'),reports:reports.filter(x=>x.status==='open'),featureable:ms.filter(x=>x.status==='published'&&x.visibility==='public'),audit:audits,stats:{profiles:users.filter(x=>x.status==='published').length,memories:ms.filter(x=>x.status==='published').length,pending:vs.filter(x=>x.status==='pending').length+ps.filter(x=>x.status==='pending').length+ms.filter(x=>x.status==='pending').length+cs.filter(x=>x.status==='pending').length+photos.filter(x=>x.status==='pending').length}})});
 app.post('/api/admin/review',async c=>{const s=factory(c),v=await viewer(c,s);if(!canModerate(v))return c.json(msg('Forbidden'),403);const x=await body(c,reviewInput);let ownerId='';if(x.type==='verification'){const row=(await s.verifications()).find(y=>y.id===x.id);if(!row)return c.json(msg('Submission not found'),404);ownerId=row.userId;await s.saveVerification({...row,status:x.status,reviewNote:x.note});if(x.status==='published'){const u=await s.userById(row.userId);if(u)await s.updateUser({...u,verified:true})}}else if(x.type==='profile'){const row=(await s.profiles()).find(y=>y.id===x.id);if(!row)return c.json(msg('Submission not found'),404);ownerId=row.userId;if(x.status==='published'&&!(await s.userById(ownerId))?.verified)return c.json(msg('Verify the alumnus first.'),409);if(x.status==='published'&&row.portrait?.startsWith('/api/photos/')&&!(await s.photos()).some(p=>'/api/photos/'+p.id===row.portrait&&p.status==='published'))return c.json(msg('Approve the portrait photo first.'),409);await s.saveProfile({...row,status:x.status,reviewNote:x.note})}else if(x.type==='memory'){const row=(await s.memories()).find(y=>y.id===x.id);if(!row)return c.json(msg('Submission not found'),404);ownerId=row.ownerId;if(x.status==='published'&&!(await s.userById(ownerId))?.verified)return c.json(msg('Verify the alumnus first.'),409);if(x.status==='published'&&row.image?.startsWith('/api/photos/')&&!(await s.photos()).some(p=>'/api/photos/'+p.id===row.image&&p.status==='published'))return c.json(msg('Approve the memory photo first.'),409);await s.saveMemory({...row,status:x.status,reviewNote:x.note})}else if(x.type==='photo'){const row=(await s.photos()).find(y=>y.id===x.id);if(!row)return c.json(msg('Submission not found'),404);ownerId=row.ownerId;await s.savePhoto({...row,status:x.status,visibility:x.status==='published'?'public':row.visibility,reviewNote:x.note})}else {const row=(await s.comments()).find(y=>y.id===x.id);if(!row)return c.json(msg('Submission not found'),404);ownerId=row.userId;await s.saveComment({...row,status:x.status,reviewNote:x.note})}await s.addDecision(v!.id,x.type,x.id,x.status,x.note);await audited(s,v!.id,'review '+x.status,x.type+':'+x.id);if(options.email){const recipient=await s.userById(ownerId);if(recipient){try{await options.email(c,recipient.email,'Alumni Gallery review update',x.status==='published'?'Your '+x.type+' was approved.':'Your '+x.type+' needs changes. '+(x.note||'Please review your submission.'))}catch(e){console.error('Email delivery failed',e)}}}return c.json({ok:true})});
 app.post('/api/admin/feature/:id',async c=>{const s=factory(c),v=await viewer(c,s);if(!canModerate(v))return c.json(msg('Forbidden'),403);const m=(await s.memories()).find(x=>x.id===c.req.param('id'));if(!m||m.status!=='published'||m.visibility!=='public')return c.json(msg('Only public published memories can be featured.'),400);await s.saveMemory({...m,featured:!m.featured});await audited(s,v!.id,'feature toggled',m.id);return c.json({featured:!m.featured})});
 app.post('/api/admin/reports/:id/resolve',async c=>{const s=factory(c),v=await viewer(c,s);if(!canModerate(v))return c.json(msg('Forbidden'),403);const r=(await s.reports()).find(x=>x.id===c.req.param('id'));if(!r)return c.json(msg('Report not found'),404);await s.saveReport({...r,status:'resolved'});await audited(s,v!.id,'report resolved',r.id);return c.json({ok:true})});
 app.put('/api/admin/batches/:year',async c=>{const s=factory(c),v=await viewer(c,s);if(v?.role!=='administrator')return c.json(msg('Forbidden'),403);const year=Number(c.req.param('year')),x=await body(c,z.object({theme:z.string().trim().min(3).max(100),subtitle:z.string().trim().max(250)}));if(year<1900||year>2100)return c.json(msg('Invalid year'),400);await s.saveBatch({year,...x});await audited(s,v.id,'batch saved',String(year));return c.json({ok:true})});
 app.put('/api/admin/programs/:id',async c=>{const s=factory(c),v=await viewer(c,s);if(v?.role!=='administrator')return c.json(msg('Forbidden'),403);const name=c.req.param('id'),x=await body(c,z.object({name:z.string().trim().min(2).max(100),short:z.string().trim().min(2).max(30)}));if(!/^[a-z0-9-]{2,40}$/.test(name))return c.json(msg('Invalid program ID'),400);await s.saveProgram({id:name,...x});await audited(s,v.id,'program saved',name);return c.json({ok:true})});
 app.delete('/api/admin/programs/:id',async c=>{const s=factory(c),v=await viewer(c,s);if(v?.role!=='administrator')return c.json(msg('Forbidden'),403);const name=c.req.param('id');if((await s.profiles()).some(x=>x.programId===name))return c.json(msg('This program is used by alumni profiles.'),409);await s.deleteProgram(name);await audited(s,v.id,'program removed',name);return c.json({ok:true})});
 return app;
}
function validImage(data:Uint8Array,type:string){if(type==='image/jpeg')return data.length>3&&data[0]===0xff&&data[1]===0xd8&&data[2]===0xff;if(type==='image/png')return data.length>8&&[137,80,78,71,13,10,26,10].every((x,i)=>data[i]===x);return data.length>12&&String.fromCharCode(...data.slice(0,4))==='RIFF'&&String.fromCharCode(...data.slice(8,12))==='WEBP'}
async function ownedPhoto(s:Store,url:string,userId:string){if(!url.startsWith('/api/photos/'))return false;const id=url.slice('/api/photos/'.length);return (await s.photos()).some(x=>x.id===id&&x.ownerId===userId)}










